version: '3'

services:
  web:
    container_name: jkh.web
    hostname: web
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf-d:/etc/nginx/conf.d
      - ./www:/var/www
  node:
    container_name: jkh.node
    hostname: node
    image: node:12.6
    working_dir: /var/jkh
    command: ./node_modules/gulp/bin/gulp.js watch
    volumes:
      - ./:/var/jkh